# Generated by Django 5.0.7 on 2024-07-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deposit_amount',
            field=models.IntegerField(blank=True, choices=[(500, '500'), (800, '800'), (1000, '1000'), (1200, '1200')], null=True),
        ),
    ]
