# Generated by Django 5.0.7 on 2024-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_alter_booking_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(upload_to='venues/'),
        ),
    ]
