# Generated by Django 5.0.7 on 2024-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
