# Generated by Django 5.0.7 on 2024-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payments_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
